name: clang-format

# if .*pp files are touched in a PR, check if they pass clang-format !

on:
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: tj-actions/changed-files@v45
      id: changed-files
      with:
        files: |
          '**/*.cpp'
          '**/*.hpp'
          '**/*.h'
          '**/*.cc'
          '**/*.cxx'
          '**/*.hxx'
    - name: clang-format
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        touch /tmp/changed_files.txt
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file" >> /tmp/changed_files.txt
        done
        clang-format --dry-run --Werror --verbose --files=/tmp/changed_files.txt
        if [ $? -ne 0 ]; then
          echo "clang-format failed"
          exit 1
        fi
        echo "clang-format passed"
